debug bazel build

diff --git a/.github/workflows/build_tensorflow.yaml b/.github/workflows/build_tensorflow.yaml
--- a/.github/workflows/build_tensorflow.yaml
+++ b/.github/workflows/build_tensorflow.yaml
@@ -62,9 +62,23 @@ jobs:
         cd tensorflow
         bazel build --define xnn_enable_avxvnniint8=false --jobs=$(nproc) --config=monolithic --verbose_failures --symlink_prefix=output/ //tensorflow/lite:libtensorflowlite.so
 
-    - name: Locate Built TensorFlow Lite Library
-      run: find . -name "libtensorflowlite.so" || echo "File not found!"
-      
+    - name: Build TensorFlowLite
+      run: |
+        cd tensorflow
+        ./configure --python_path=/usr/bin/python3
+        bazel build --python_path=/usr/bin/python3 --define xnn_enable_avxvnniint8=false --jobs=$(nproc) --config=monolithic --verbose_failures --symlink_prefix=output/ //tensorflow/lite:libtensorflowlite.so
+
+    - name: Debug Bazel Output Directory
+      run: ls -R bazel-bin/ || echo "bazel-bin directory not found!"
+
+    - name: Debug Bazel Output with Symlink Prefix
+      run: ls -R output/bin/ || echo "output/bin directory not found!"
+
+    - name: Analyze Bazel Query
+      run: |
+        cd tensorflow
+        bazel aquery //tensorflow/lite:libtensorflowlite.so
+
     # 7. Copy Necessary Files
     - name: Prepare Libraries and Headers
       run: |
